services:
  postgis:
    image: postgres
    container_name: sass-study-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sass-study
      POSTGRES_PASSWORD: Ld89gh-ZNs-2m-s91-82x-2GA-l
      POSTGRES_DB: sass-study
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: sass-study-redis
    ports:
      - "6379:6379"
volumes:
  postgres_data:
